wallpaper {
    monitor = DP-5
    path = /home/daniel/Pictures/Wallpapers/45e2ab52d01a964d60aed70b71315d5b.png
}

wallpaper {
    monitor = eDP-1
    path = /home/daniel/Pictures/Wallpapers/45e2ab52d01a964d60aed70b71315d5b.png
}
